###################################################
### OVERRIDE DEFAULT DOCKER-COMPOSE CONFIG FILE ###
### SERVICES CAN BE REMOVED IF YOU NOT CHANGING ###
###################################################

# CONFIG
version: '2'

# SERVICES
services:
  # APP
  app:
    ports:
      - 80:8080
      - 443:8083

  # smtp
  smtp:
    ports:
      - 1025:1025
      - 2080:8025

  # db
  db:
    ports:
      - 4306:3306

  # REDIS
   cache:
     ports:
       - 7379:6379
